### PR TITLE
Merge state at commit ca06fc273acec789266678dc2565e27ad0be11ad

### PR DESCRIPTION
**Pull request by cerna**
This pull request merges in changes from upstream LinuxCNC@master branch at commit ca06fc273acec789266678dc2565e27ad0be11ad (the latest commit with fully passed tests at LinuxCNC's buildbot operation).

I have been talking about rebuilding and upgrading the packages in #6, however the situation ended up so that enough time passed to justify merging in changes beforehand. 

Checked locally in simulation mode on `amd64`.

### CODE REVIEW

**Comment by zultron** [comment]
Thanks for keeping this up to date!

**Comment by cerna** [comment]
EMCApplication from this version is uploaded in the Cloudsmith repository.

The `armhf` version requires a special version of Machinekit-HAL (as @the-snowwhite wanted) which is also in the Machinekit-HAL Cloudsmith repository. (Tested in foreign architecture docker environment.)

Sorry it took so long!

**Comment by the-snowwhite** [comment]
Thanks
I seem to be stuck in attempting to get anywhere with reviving the mkwrapper functionality before I can get to any real testing...

**Comment by the-snowwhite** [comment]
tested to fix the setuid issue on armhf
Great to also see the mksocfpga packages

**Pull request merged**
